server:
  port: 8090

yinn:
  swagger:
    enabled: true
    auth-key: Yinn-Token
    docket:
      base:
        title: Yinn接口文档
        base-package: top.yinn
      system:
        title: 系统基础接口文档
        base-package: top.yinn.modulars.system.controller
      test:
        title: 测试文档
        base-package: top.yinn.modulars.test.controller
  sa-token:
    # jwt 集成模式  Simple(简单模式)、Mixin(混入模式)、Stateless(无状态模式)
    # 详细查看sa-token官方文档
    jwt: Mixin
    token-name: ${yinn.swagger.auth-key}

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  mvc:
    pathmatch:
      # Boot 2.6+ 默认的路由匹配策略，Swagger 暂不兼容，使用老策略
      matching-strategy: ant_path_matcher
  profiles:
    active: @pom.profile.name@
