server:
  port: 8090

yinn:
  mysql:
    ip: yinn
    port: 3306
    driverClassName: com.mysql.cj.jdbc.Driver
    database: yinn-db
    username: root
    password: yinn357
  database:
    isBlockAttack: false  # 是否启用 攻击 SQL 阻断解析器
  redis:
    ip: 127.0.0.1
    port: 6379
    password:
    database: 0
  swagger:
    enabled: true
    docket:
      base:
        title: Yinn接口文档
        base-package: top.yinn
      test:
        title: 测试文档
        base-package: top.yinn.modulars.test.controller
  sa-token:
    # jwt 集成模式  Simple(简单模式)、Mixin(混入模式)、Stateless(无状态模式)
    # 详细查看sa-token官方文档
    jwt: Stateless

#j2cache:
#  l2-cache-open: true #开启二级缓存

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  mvc:
    pathmatch:
      # Boot 2.6+ 默认的路由匹配策略，Swagger 暂不兼容，使用老策略
      matching-strategy: ant_path_matcher